blog/blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # post views
    path('', views.PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/',
         views.PostListView.as_view(), name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.PostDetail.as_view(),
         name='post_detail'),
    path('<int:post_id>/share/',
         views.PostShareFormView.as_view(), name='post_share'),
    path('search/', views.PostSearchFormView.as_view(), name='post_search')
]

app_name = 'blog'

blog/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog'))
]

blog/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (('draft', 'Draft'),
                      ('published', 'Published'))
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10,
        default='published',
        choices=STATUS_CHOICES
    )
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year, self.publish.month,
                             self.publish.day, self.slug])

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(to=Post, on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comment = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField(max_length=80)

blog/blog/views.py
from django.conf import settings
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import (
    ListView,
    DetailView,
    TemplateView
)
from django.core.mail import send_mail
from django.contrib.postgres.search import SearchVector
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import FormView
from django.views import View
from django.views.generic.list import MultipleObjectMixin

from taggit.models import Tag
from .models import Post
from .forms import EmailPostForm, CommentForm, SearchForm


class PostListView(ListView):
    template_name = 'blog/post/list.html'
    context_object_name = 'posts'
    model = Post
    paginate_by = 3
    tag = None

    def dispatch(self, request, tag_slug=None, *args, **kwargs):
        if tag_slug:
            self.tag = get_object_or_404(Tag, slug=tag_slug)
        return super(PostListView, self).dispatch(
            request, tag=None, *args, **kwargs
        )

    def get_queryset(self):
        queryset = super(PostListView, self).get_queryset().prefetch_related(
            'tags'
        ).select_related('author')
        if self.tag:
            queryset = queryset.filter(tags=self.tag)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super(PostListView, self).get_context_data(
            object_list=None, **kwargs
        )
        context_data.update({'tag': self.tag})
        return context_data


class PostCommentsMixin:
    template_name = 'blog/post/detail.html'
    slug_url_kwarg = 'post'
    context_object_name = 'post'
    model = Post

    def get_queryset(self):
        queryset = super(PostCommentsMixin, self).get_queryset()
        year, month, day = self.resolve_year_month_date().values()

        return queryset.filter(
            publish__year=year,
            publish__month=month,
            publish__day=day
        )

    def resolve_year_month_date(self):
        return dict(
            year=self.kwargs['year'],
            month=self.kwargs['month'],
            day=self.kwargs['day']
        )


class PostDetailView(PostCommentsMixin, DetailView):
    def get_context_data(self, **kwargs):
        context_data = super(PostDetailView, self).get_context_data(**kwargs)
        comments = self.object.comments.filter(active=True)
        similar_posts = self.object.tags.similar_objects()
        context_data.update({
            'comments': comments,
            'similar_posts': similar_posts,
            'form': CommentForm()
        })
        return context_data


class PostComment(PostCommentsMixin, SingleObjectMixin, FormView):
    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.post = self.get_object()
            new_comment.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_success_url(self):
        return reverse(
            'blog:post_detail',
            kwargs={
                **self.resolve_year_month_date(),
                self.slug_url_kwarg: self.kwargs[self.slug_url_kwarg]
            }
        )


class PostDetail(View):
    def get(self, request, *args, **kwargs):
        view = PostDetailView.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = PostComment.as_view()
        return view(request, *args, **kwargs)


class PostShareFormView(FormView):
    template_name = 'blog/post/share.html'
    form_class = EmailPostForm
    post_to_sent = None

    def dispatch(self, request, post_id, *args, **kwargs):
        self.post_to_sent = get_object_or_404(Post.published.all(),
                                      id=post_id)
        return super(PostShareFormView, self).dispatch(
            request,
            *args,
            **kwargs
        )

    def get_success_url(self):
        return reverse(
            'blog:post_detail',
            kwargs={
                'year': self.post_to_sent.publish.year,
                'month': self.post_to_sent.publish.month,
                'day': self.post_to_sent.publish.day,
                'post': self.post_to_sent.slug
            }
        )

    def form_valid(self, form):
        post_url = self.request.build_absolute_uri(
            self.post_to_sent.get_absolute_url()
        )
        cleaned_data = form.cleaned_data
        subject = f'{cleaned_data["name"]} ({cleaned_data["email"]}) ' \
                  f'recommends you reading {self.post_to_sent.title}'
        message = f'Read "{self.post_to_sent.title}" at {post_url}\n\n' \
                  f'{cleaned_data["name"]}\'s comments: ' \
                  f'{cleaned_data["comment"]}'

        send_mail(subject, message, settings.EMAIL_HOST_USER,
                  [cleaned_data['to']])

        return super(PostShareFormView, self).form_valid(form=form)

    def get_context_data(self, **kwargs):
        context_data = super(PostShareFormView, self).get_context_data(
            **kwargs
        )
        context_data.update({
            'post': self.post_to_sent,
        })
        return context_data


class PostSearchFormView(MultipleObjectMixin, TemplateView):
    template_name = 'blog/post/search.html'
    model = Post

    def get_queryset(self, query=None):
        queryset = super(PostSearchFormView, self).get_queryset()
        if query:
            queryset = queryset.annotate(search=SearchVector(
                'title', 'body'
            )).filter(search=query)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(
            object_list=self.get_queryset(),
            **kwargs
        )

        form = SearchForm()
        if self.request.GET.get('query'):
            form = SearchForm(self.request.GET)

        if form.is_valid():
            query = form.cleaned_data['query']
            results = self.get_queryset(query=query)
            context_data.update({
                'query': query,
                'results': results
            })
        context_data['form'] = form
        return context_data

blog/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>

    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|linebreaks }}
    <p>
        <a href="{% url "blog:post_share" post.id %}">
            Share this post
        </a>
    </p>

    <h2>Similar posts</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        There are no similar posts yet.
    {% endfor %}

    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}

    <h2>Add a new comment</h2>
    <form action="" method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Add comment"></p>
    </form>
{% endblock %}

blog/blog/templates/blog/post/latest_posts.html
<ul>
 {% for post in latest_posts %}
 <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
 {% endfor %}
</ul>

blog/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}My Blog{% endblock %}

{% block content %}
    <h1>My Blog</h1>
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>
        <p class="tags">
            Tags:
            {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                    {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|truncatewords:30|linebreaks }}
    {% endfor %}
    {% include "pagination.html" with page=page_obj %}
{% endblock %}

blog/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% block title %}Search{% endblock %}
{% block content %}
    {% if results %}
        <h1>Posts containing "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
                Found {{ total_results }} result {{ total_results|pluralize }}
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
            {{ post.body|truncatewords:5 }}
        {% empty %}
            <p>There are no results for your query.</p>
        {% endfor %}
        <p><a href="{% url "blog:post_search" %}">Search again</a></p>
    {% else %}
        <h1>Search for posts</h1>
        <form action="." method="get">
            {{ form.as_p }}
            <input type="submit" value="Search">
        </form>
    {% endif %}
{% endblock %}

blog/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
{% if messages %}
 <ul class="messages">
 {% for message in messages %}
 <li class="{{ message.tags }}">
 {{ message|safe }}
 <a href="#" class="close">x</a>
 </li>
 {% endfor %}
 </ul>
{% endif %}
<h1>Share "{{ post.title }}" by e-mail</h1>
<form action="." method="post">
    {{ form.as_table }}
    {% csrf_token %}
    <input type="submit" value="Send e-mail">
</form>
{% endblock %}